android.nonTransitiveRClass=false
android.useAndroidX=true

kotlin.code.style=official
kotlin.mpp.androidSourceSetLayoutVersion=2

# Limit Gradle JVM RAM to 2.5 GB (prevents RAM exhaustion)
org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -Dfile.encoding=UTF-8

# Limit parallel CPU workers to 2 threads (prevents SSD disk thrashing)
org.gradle.workers.max=2

# Caching & performance flags
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Automatically kill idle build daemons after 5 minutes
org.gradle.daemon.idletimeout=300000


